/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://u2ijq3x74bb3tetkougiefi2uq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r7lyxd6ru5fwtcndnajt3f3anm",
    "aws_cognito_identity_pool_id": "us-east-1:99f4452f-66b3-4879-a957-ac79a0d6ebd0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NuNrW2eeR",
    "aws_user_pools_web_client_id": "241k6nq6h6rdhrhhe7n211b265",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "customers-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "events-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
